stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
      - src/get_data.py
      - src/load_data.py
      - data_given/winequality.csv
    outs:
      - data/raw/winequality.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
      - src/load_data.py
      - src/split_data.py
      - data/raw/winequality.csv
    outs:
      - data/processed/train_winequality.csv
      - data/processed/test_winequality.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
      - src/load_data.py
      - src/split_data.py
      - src/train_and_evaluate.py
      - data/processed/train_winequality.csv
      - data/processed/test_winequality.csv
    outs:
      - saved_models/model.joblib